language: php

php:
- 7.2.0

branches:
  except:
  #  - develop
  #  - master
  - /^feature.*$/

install:
- composer install

before_script:
- phpenv config-add travis-config.ini

script:
- vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
